function [lambda] = IsoDispRelMakerDiscrete(kx,ky,km,D_pos,D_rot,bc,dt)

lambda = -( D_pos .* ( kx.^2 + ky.^2 ) + D_rot .* km.^2  )  + ...
          1 / dt .* log( 1 + ...
           ( 1 + (-1).^( km ) ) .* ...
           bc .* dt .* ( D_pos .* ( kx.^2 + ky.^2 ) + D_rot .* km.^2  ) ...
           ./ ( km.^2 - 1 + 0.0000001 ) ) ;

end