function [rho_FT_next] = ...
          DenStepperAB3Cube(Prop,rho_FT, GammaEx_FT,GammaEx_FT_prev,GammaEx_FT_prev2,dt)

% Step using the hybrid AB. Everything is still in cube form.
rho_FT_next = Prop .* ( rho_FT ...
    + dt * ( 23/12 * GammaEx_FT ...
            + Prop .* (-4/3 * GammaEx_FT_prev + 5/12 * Prop .* GammaEx_FT_prev2)) );
end